# Generated by Django 3.1 on 2021-06-17 16:08

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Camp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('date', models.CharField(max_length=1000)),
                ('camp_topic', models.CharField(max_length=1000)),
                ('description', ckeditor.fields.RichTextField()),
                ('banner', models.ImageField(upload_to='banners/')),
                ('camp_logo', models.ImageField(upload_to='logos/')),
                ('paid', models.CharField(choices=[('Paid', 'Paid'), ('Free', 'Free')], max_length=20)),
                ('registration_fee', models.FloatField(default=0)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Ongoing', 'Ongoing'), ('Upcoming', 'Upcoming'), ('Held', 'Held')], default='Upcoming', max_length=20)),
                ('code', models.CharField(max_length=100)),
                ('from_class', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], max_length=20)),
                ('to_class', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('12+', '12+')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CampTrainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('instituion', models.CharField(max_length=1000)),
                ('work', models.CharField(max_length=1000)),
                ('image', models.ImageField(default='/user.png', upload_to='camp_trainers/')),
                ('chief', models.BooleanField()),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainers', to='camp.camp')),
            ],
        ),
        migrations.CreateModel(
            name='CampParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_id', models.CharField(max_length=100)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('camper_class', models.CharField(max_length=20)),
                ('camper_category', models.CharField(max_length=20)),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campers', to='camp.camp')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CampOrganizer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('image', models.ImageField(default='/user.png', upload_to='camp_organizer/')),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizers', to='camp.camp')),
            ],
        ),
        migrations.CreateModel(
            name='CampContestParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c_campers', to='camp.campparticipant')),
            ],
        ),
        migrations.CreateModel(
            name='CampContest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('status', models.CharField(choices=[('Ongoing', 'Ongoing'), ('Upcoming', 'Upcoming'), ('Held', 'Held')], max_length=20)),
                ('description', ckeditor.fields.RichTextField()),
                ('date', models.CharField(max_length=1000)),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camp_contest', to='camp.camp')),
            ],
        ),
        migrations.CreateModel(
            name='CampAnnouncement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announce', ckeditor.fields.RichTextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announces', to='camp.camp')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announces', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
