# Generated by Django 3.1 on 2021-06-02 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_problemtag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problemtag',
            old_name='probelm',
            new_name='problem',
        ),
    ]
