# Generated by Django 3.1 on 2021-06-02 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210602_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemtried',
            name='ans',
            field=models.FloatField(default=10.0),
            preserve_default=False,
        ),
    ]
