# Generated by Django 3.1 on 2021-06-05 06:21

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_problemtried_ans'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('date', models.CharField(max_length=1000)),
                ('camp_topic', models.CharField(max_length=1000)),
                ('description', ckeditor.fields.RichTextField()),
                ('paid', models.CharField(choices=[('Paid', 'Paid'), ('Free', 'Free')], max_length=20)),
                ('registration_fee', models.FloatField(default=0)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
