# Generated by Django 3.1 on 2021-06-05 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210605_1221'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Camp',
        ),
    ]
