# Generated by Django 3.1 on 2021-06-05 06:28

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_delete_camp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('date', models.CharField(max_length=1000)),
                ('camp_topic', models.CharField(max_length=1000)),
                ('description', ckeditor.fields.RichTextField()),
                ('banner', models.ImageField(upload_to='banners/')),
                ('camp_logo', models.ImageField(upload_to='logos/')),
                ('paid', models.CharField(choices=[('Paid', 'Paid'), ('Free', 'Free')], max_length=20)),
                ('registration_fee', models.FloatField(default=0)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
