# Generated by Django 3.1 on 2021-06-13 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20210613_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='point',
            field=models.IntegerField(default=0),
        ),
    ]
