# Generated by Django 3.1 on 2021-06-14 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_camptrainer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camptrainer',
            old_name='institutuion',
            new_name='instituion',
        ),
    ]
