# Generated by Django 3.1 on 2021-06-14 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20210614_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='camptrainer',
            name='chief',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
