# Generated by Django 3.1 on 2021-06-14 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_camporganizer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CampOrganizer',
        ),
    ]
