# Generated by Django 3.1 on 2021-06-15 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0020_camporganizer'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_id', models.IntegerField(default=0)),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campers', to='app.camp')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
