# Generated by Django 3.1 on 2021-06-15 07:19

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0021_campparticipant'),
    ]

    operations = [
        migrations.AddField(
            model_name='campparticipant',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CampAnnouncement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announce', ckeditor.fields.RichTextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announces', to='app.camp')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announces', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
