# Generated by Django 3.1 on 2021-06-15 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_camp_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='camp',
            name='code',
            field=models.CharField(default='TMCC', max_length=100),
            preserve_default=False,
        ),
    ]
