# Generated by Django 3.1 on 2021-06-15 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_campparticipant_camper_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='campparticipant',
            name='camper_category',
            field=models.CharField(default='Primary', max_length=20),
            preserve_default=False,
        ),
    ]
