# Generated by Django 3.1 on 2021-06-16 07:09

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20210615_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campparticipant',
            name='reg_id',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='CampContest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('status', models.CharField(choices=[('Ongoing', 'Ongoing'), ('Upcoming', 'Upcoming'), ('Held', 'Held')], max_length=20)),
                ('description', ckeditor.fields.RichTextField()),
                ('date', models.CharField(max_length=1000)),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camp_contest', to='app.camp')),
            ],
        ),
    ]
