# Generated by Django 3.1 on 2021-06-16 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20210616_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampContestParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c_campers', to='app.campparticipant')),
            ],
        ),
    ]
