# Generated by Django 3.1 on 2021-06-17 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_campcontestparticipant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campannouncement',
            name='camp',
        ),
        migrations.RemoveField(
            model_name='campannouncement',
            name='user',
        ),
        migrations.RemoveField(
            model_name='campcontest',
            name='camp',
        ),
        migrations.RemoveField(
            model_name='campcontestparticipant',
            name='user',
        ),
        migrations.RemoveField(
            model_name='camporganizer',
            name='camp',
        ),
        migrations.RemoveField(
            model_name='campparticipant',
            name='camp',
        ),
        migrations.RemoveField(
            model_name='campparticipant',
            name='user',
        ),
        migrations.RemoveField(
            model_name='camptrainer',
            name='camp',
        ),
        migrations.DeleteModel(
            name='Camp',
        ),
        migrations.DeleteModel(
            name='CampAnnouncement',
        ),
        migrations.DeleteModel(
            name='CampContest',
        ),
        migrations.DeleteModel(
            name='CampContestParticipant',
        ),
        migrations.DeleteModel(
            name='CampOrganizer',
        ),
        migrations.DeleteModel(
            name='CampParticipant',
        ),
        migrations.DeleteModel(
            name='CampTrainer',
        ),
    ]
