# Generated by Django 3.1 on 2021-08-18 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20210617_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='status',
            field=models.CharField(choices=[('Public', 'Public'), ('Hidden', 'Hidden')], default='Public', max_length=20),
            preserve_default=False,
        ),
    ]
