# Generated by Django 3.1 on 2021-08-29 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_clubmember'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClubMember',
        ),
    ]
