# Generated by Django 3.1 on 2021-08-29 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_delete_clubmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20000)),
                ('dept', models.CharField(max_length=500)),
                ('post', models.CharField(max_length=500)),
                ('time', models.DateField(auto_now=True)),
                ('image', models.ImageField(default='/user.png', upload_to='image/')),
            ],
        ),
    ]
