# Generated by Django 3.1 on 2021-08-29 18:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_clubmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='bangla',
            field=ckeditor.fields.RichTextField(default='Bangla'),
            preserve_default=False,
        ),
    ]
